# mkdocsignore: false
# include_glob:
#   - "test/test.md"
#   - "**/draft-*.md"
# include_tag:
#   - foo
#   - "#bar"
# exclude_tag:
#   - "#bar"

# INCLUDE ONLY DOC TAGED WITH 'released'
# only_doc_pages: true
# exclude_regex:
#   - '.*\.md$'
# include_tag:
#   - released

only_doc_pages: true # default value is false
mkdocsignore: true
include_tag:
  - released
include_regex:
  - "tags.md"
