# mkdocsignore: false
# include_glob:
#   - "test/test.md"
#   - "**/draft-*.md"
# exclude_glob:
#   - "Contributions/**"
# include_tag:
#   - foo
#   - "#bar"
# exclude_tag:
#   - test

only_doc_pages: true # default value is false
exclude_regex:
  - '.*\.md$'
include_regex:
  - "tags.md"
include_tag:
  - released
