default_language_version:
  python: python3.10

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: (.github|mkdocs.*.yml)
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: check-toml
      - id: debug-statements
      - id: no-commit-to-branch
      - id: check-case-conflict
      - id: check-docstring-first

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry poe pyupgrade
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry poe ruff-fix
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry poe isort-fix
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry poe black-fix
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry poe flake8
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: pydocstyle
        name: pydocstyle
        entry: poetry poe pydocstyle
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry poe pre-commit-mypy
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry poe pylint
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: poetry poe pre-commit-bandit
        types: [python]
        language: system
