INHERIT: mkdocs.base.yml

#! dev_addr: 127.0.0.1:1357

plugins:
  - search
  - tags:
      tags_file: tags.md
  - file-filter:
      config: !ENV [MY_FILE_FILTER_CONFIG, "mkdocs.file-filter.yml"]
      # metadata_property: labels
      # exclude_tag:
      #   - test
