INHERIT: mkdocs.base.yml

#! dev_addr: 127.0.0.1:1357

plugins:
  - search
  # - monorepo
  - tags:
      tags_file: tags.md
  - awesome-pages
  - file-filter:
      config: !ENV [MY_FILE_FILTER_CONFIG, ".file-filter.yml"]
      enabled: !ENV [CI, true]
      enabled_on_serve: true
      filter_nav: true
      only_doc_pages: true
