INHERIT: mkdocs.base.yml

plugins:
  - search
  - file-filter:
      config: !ENV [MY_FILE_FILTER_CONFIG, ".file-filter.yml"]
      # enabled: !ENV [CI, true]
      # enabled_on_serve: true
      # filter_nav: true
      # only_doc_pages: true
