---
name: Release

# on:
#   release:
#     types:
#       - prereleased
#       - released
#       - published

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Set Version
        run: poetry version ${GITHUB_REF_NAME/v/}

      - name: Build
        run: poetry build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: |
            dist/*
            schema*.json

  gh-release:
    name: GitHub Release
    needs: build
    environment:
      name: GitHub
      url: ${{ steps.gh-release.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: plugin
          path: artifact

      - run: |
          cd artifact
          tree

      - name: Release
        id: gh-release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            artifact/dist/*
            artifact/schema*.json

  pypi-release:
    name: PyPI Release
    needs: gh-release
    # if: ${{ !github.event.release.prerelease && github.event.action == 'released' && github.repository_owner == 'DariuszPorowski' }}
    environment:
      name: PyPI
      url: "https://pypi.org/project/mkdocs-file-filter-plugin"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"
      #     cache: "poetry"

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: plugin
          path: .

      - run: |
          tree

      - name: Publish to PyPI
        run: poetry publish --dry-run --verbose --username=__token__ --password ${{ secrets.PYPI_API_TOKEN }}
