---
name: Draft New Release

on:
  workflow_dispatch:

permissions: write-all

jobs:
  release-draft:
    if: github.repository_owner == 'DariuszPorowski'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release URL
        run: |
          echo "${RELEASE_URL}"
          echo "${RELEASE_URL}" >> $GITHUB_STEP_SUMMARY
        env:
          RELEASE_URL: ${{ steps.release-drafter.outputs.html_url }}
