---
name: Pull Request checker
on: pull_request

jobs:
  pr:
    if: github.repository_owner == 'DariuszPorowski'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        run: |
          pip install poetry
          poetry --version

      - name: Test Build
        run: |
          poetry version
          poetry build
