---
name: Pull Request checker
on:
  pull_request:
    branches:
      - main

# Allow one concurrent
concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --only=dev

      - name: Check imports sort
        run: poetry run isort --check-only .

      - name: Check formatting
        run: poetry run black --check .

      - name: Check formatting
        run: poetry run flake8 --count .

  test:
    name: Test
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "pypy-3.8"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Test Build
        run: |
          poetry version
          poetry build --verbose

      - name: Test MkDocs build
        run: |
          pip uninstall -y mkdocs_file_filter_plugin
          pip install dist/mkdocs_file_filter_plugin-0.0.1.tar.gz
          poetry run mkdocs build --verbose
