---
name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ format('{0}-{1}', github.event_name, github.ref) }}
  cancel-in-progress: true

permissions: {}

jobs:
  release-draft:
    if: ${{ github.repository_owner == 'DariuszPorowski' }}
    name: Draft Release
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Release URL
        run: |
          echo "${RELEASE_URL}"
          echo "${RELEASE_URL}" >> $GITHUB_STEP_SUMMARY
        env:
          RELEASE_URL: ${{ steps.release-drafter.outputs.html_url }}
