---
name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  pypi-release:
    name: PyPI Release
    environment:
      name: PyPI
      url: "https://pypi.org/project/mkdocs-file-filter-plugin"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --verbose

      - name: Set Version
        run: poetry version ${GITHUB_REF_NAME/v/}

      - name: Build
        run: poetry build --verbose

      - name: Publish to PyPI
        run: poetry publish --verbose --username=__token__ --password ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: |
            dist/*
            schema*.json

  gh-release:
    name: GitHub Release
    needs: pypi-release
    environment:
      name: GitHub
      url: ${{ steps.gh-release.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: plugin
          path: .

      - name: Release
        id: gh-release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            dist/*
            schema*.json
